services:
    postgres:
        container_name: db
        image: postgres:15
        env_file:
            - .env
        environment:
            - POSTGRES_DB=${DB_NAME:?error}
            - POSTGRES_USER=${DB_USERNAME:?error}
            - POSTGRES_PASSWORD=${DB_PASSWORD:?error}
        volumes:
            - ./pg_data:/var/lib/postgresql/data
        ports:
            - ${DB_PORT}:5432

# Important notest here! This gets confusing easily

# In your docker desktop gui:
# - the STACK will be called "gowild"
# - the CONTAINER for the database will be called "db"
# - the actual database you log into is called whatever you specify in your .env